#' Classify Fishing Effort into Low, Medium, High Categories
#'
#' This function takes the aggregated fishing effort `sf` object generated by
#' `grid_aggregate_sf()` and adds four categorical variables:
#'   - fishing_hours_cat: based on raw total fishing hours
#'   - fishing_kw_cat: based on raw total fishing kW-hours
#'   - fishing_hours_log_cat: based on log10(total fishing hours + 1)
#'   - fishing_kw_log_cat: based on log10(total fishing kW-hours + 1)
#'
#' Categories are defined using quartiles: 
#'   - Low: values ≤ Q1
#'   - Medium: Q1 < values ≤ Q3
#'   - High: values > Q3
#'
#' @param sf_obj An `sf` object returned by `grid_aggregate_sf()`.
#'
#' @return An `sf` object with four new categorical columns.
#' @export
#'
#' @examples
#' \dontrun{
#' agg <- grid_aggregate_sf("data-raw/agg_cell_gear_mzc_rob.rds", grid_size = 0.1)
#' classified <- classify_fishing_effort(agg)
#' }
#'
#' @import dplyr
#'
classify_fishing_effort <- function(sf_obj) {
  # Validate input
  stopifnot(inherits(sf_obj, "sf"))
  
  # --- Helper to classify based on quartiles ---
  classify_quartiles <- function(x) {
    if (all(is.na(x))) return(rep(NA, length(x))) # Handle all NAs
    q <- quantile(x, probs = c(0.25, 0.75), na.rm = TRUE)
    cut(
      x,
      breaks = c(-Inf, q[1], q[2], Inf),
      labels = c("Low", "Medium", "High"),
      include.lowest = TRUE,
      right = TRUE
    )
  }
  
  # --- Raw values classification ---
  sf_obj <- sf_obj |>
    dplyr::mutate(
      fishing_hours_cat    = classify_quartiles(total_fishing_hours),
      fishing_kw_cat       = if ("total_fishing_kw_hours" %in% names(sf_obj)) {
        classify_quartiles(total_fishing_kw_hours)
      } else NA
    )
  
  # --- Log-transformed classification ---
  sf_obj <- sf_obj |>
    dplyr::mutate(
      fishing_hours_log_cat = classify_quartiles(log10(total_fishing_hours + 1)),
      fishing_kw_log_cat    = if ("total_fishing_kw_hours" %in% names(sf_obj)) {
        classify_quartiles(log10(total_fishing_kw_hours + 1))
      } else NA
    )
  
  return(sf_obj)
}